# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis configuration'
  inputs:
    SonarCloud: 'Sonarcloud Service Connection'
    organization: 'digitaldelivery'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectName = SPOT-Android
      sonar.projectKey = SPOT-Android

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleDebug'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '2.6.1'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
